spring:
  datasource:
    url: jdbc:mysql://rm-wz917wbvou67a757quo.mysql.rds.aliyuncs.com:3306/movies?useUnicode=true&characterEncoding=utf8&useSSL=true
    username: saxon
    password: 19990707
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    #配置监控统计拦截的filters，stat：监控统计、log4j：日志记录、wall：防御sql注入
    #如果允许报错，java.lang.ClassNotFoundException: org.apache.Log4j.Properity
    #则导入log4j 依赖就行
    filters: stat,wall,log4j
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionoProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
  thymeleaf:
    cache: false

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    default-statement-timeout: 10000
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl



server:
  port: 8080

